-- Bước 1: Chuyển đổi kiểu dữ liệu
ALTER TABLE sales_dataset_rfm_prj
ALTER COLUMN ORDERNUMBER TYPE INT USING ORDERNUMBER::integer,
ALTER COLUMN QUANTITYORDERED TYPE INT USING QUANTITYORDERED::integer,
ALTER COLUMN PRICEEACH TYPE DECIMAL(10, 2) USING PRICEEACH::numeric(10, 2),
ALTER COLUMN ORDERLINENUMBER TYPE INT USING ORDERLINENUMBER::integer,
ALTER COLUMN SALES TYPE DECIMAL(10, 2) USING SALES::numeric(10, 2),
ALTER COLUMN ORDERDATE TYPE DATE USING ORDERDATE::date;

-- Bước 2: Kiểm tra NULL/BLANK
SELECT *
FROM sales_dataset_rfm_prj
WHERE ORDERNUMBER IS NULL OR QUANTITYORDERED IS NULL OR PRICEEACH IS NULL OR ORDERLINENUMBER IS NULL OR SALES IS NULL OR ORDERDATE IS NULL;

-- Bước 3: Thêm cột CONTACTLASTNAME, CONTACTFIRSTNAME
ALTER TABLE sales_dataset_rfm_prj
ADD COLUMN CONTACTLASTNAME VARCHAR(255),
ADD COLUMN CONTACTFIRSTNAME VARCHAR(255);

UPDATE sales_dataset_rfm_prj
SET CONTACTLASTNAME = SPLIT_PART(CONTACTFULLNAME, ' ', 2),
    CONTACTFIRSTNAME = SPLIT_PART(CONTACTFULLNAME, ' ', 1);

-- Bước 4: Chuẩn hóa CONTACTLASTNAME, CONTACTFIRSTNAME
UPDATE sales_dataset_rfm_prj
SET CONTACTLASTNAME = INITCAP(CONTACTLASTNAME),
    CONTACTFIRSTNAME = INITCAP(CONTACTFIRSTNAME);

-- Bước 5: Thêm cột QTR_ID, MONTH_ID, YEAR_ID
ALTER TABLE sales_dataset_rfm_prj
ADD COLUMN QTR_ID INT,
ADD COLUMN MONTH_ID INT,
ADD COLUMN YEAR_ID INT;

UPDATE sales_dataset_rfm_prj
SET QTR_ID = EXTRACT(QUARTER FROM ORDERDATE),
    MONTH_ID = EXTRACT(MONTH FROM ORDERDATE),
    YEAR_ID = EXTRACT(YEAR FROM ORDERDATE);

-- Bước 6: Tìm và xử lý outliers
-- Tạo bảng mới để lưu dữ liệu đã làm sạch
CREATE TABLE SALES_DATASET_RFM_PRJ_CLEAN AS
SELECT *
FROM sales_dataset_rfm_prj;
