-- Bước 1: Chuyển đổi kiểu dữ liệu
ALTER TABLE sales_dataset_rfm_prj
ALTER COLUMN ORDERNUMBER TYPE INT USING ORDERNUMBER::integer,
ALTER COLUMN MSRP TYPE INT USING MSRP::integer,
ALTER COLUMN QUANTITYORDERED TYPE INT USING QUANTITYORDERED::integer,
ALTER COLUMN PRICEEACH TYPE DECIMAL(10, 2) USING PRICEEACH::numeric(10, 2),
ALTER COLUMN ORDERLINENUMBER TYPE INT USING ORDERLINENUMBER::integer,
ALTER COLUMN SALES TYPE DECIMAL(10, 2) USING SALES::numeric(10, 2),
ALTER COLUMN ORDERDATE TYPE DATE USING ORDERDATE::date;

-- Bước 2: Kiểm tra NULL/BLANK
SELECT *
FROM sales_dataset_rfm_prj
WHERE ORDERNUMBER IS NULL OR QUANTITYORDERED IS NULL OR PRICEEACH IS NULL OR ORDERLINENUMBER IS NULL OR SALES IS NULL OR ORDERDATE IS NULL;

-- Bước 3: Thêm cột CONTACTLASTNAME, CONTACTFIRSTNAME
ALTER TABLE sales_dataset_rfm_prj
ADD COLUMN CONTACTLASTNAME VARCHAR(255),
ADD COLUMN CONTACTFIRSTNAME VARCHAR(255);

UPDATE sales_dataset_rfm_prj
SET CONTACTLASTNAME = SPLIT_PART(CONTACTFULLNAME, ' ', 2),
    CONTACTFIRSTNAME = SPLIT_PART(CONTACTFULLNAME, ' ', 1);

-- Chuẩn hóa CONTACTLASTNAME, CONTACTFIRSTNAME
UPDATE sales_dataset_rfm_prj
SET CONTACTLASTNAME = INITCAP(CONTACTLASTNAME),
    CONTACTFIRSTNAME = INITCAP(CONTACTFIRSTNAME);

-- Bước 4: Thêm cột QTR_ID, MONTH_ID, YEAR_ID
ALTER TABLE sales_dataset_rfm_prj
ADD COLUMN QTR_ID INT,
ADD COLUMN MONTH_ID INT,
ADD COLUMN YEAR_ID INT;

UPDATE sales_dataset_rfm_prj
SET QTR_ID = EXTRACT(QUARTER FROM ORDERDATE),
    MONTH_ID = EXTRACT(MONTH FROM ORDERDATE),
    YEAR_ID = EXTRACT(YEAR FROM ORDERDATE);

-- Bước 5: Tìm và xử lý outliers
--Cách 1: Z-score
--Tìm Z-score cho mỗi giá trị trong cột QUANTITYORDERED:
SELECT *,
       (QUANTITYORDERED - AVG(QUANTITYORDERED) OVER ()) / STDDEV(QUANTITYORDERED) OVER () AS z_score
FROM sales_dataset_rfm_prj;
--Chọn ngưỡng Z-score để xác định outliers, chọn ngưỡng là 3 hoặc -3.
--Xóa bản ghi có Z-score nằm ngoài ngưỡng:
DELETE FROM sales_dataset_rfm_prj
WHERE QUANTITYORDERED < 3 AND QUANTITYORDERED > -3;
--Hoặc cập nhật giá trị outliers về giá trị giới hạn (3 hoặc -3):
UPDATE sales_dataset_rfm_prj
SET QUANTITYORDERED = 3
WHERE QUANTITYORDERED > 3;
UPDATE sales_dataset_rfm_prj
SET QUANTITYORDERED = -3
WHERE QUANTITYORDERED < -3;

--Cách 2: IQR (Interquartile Range)
--Tìm giá trị Q1 và Q3 của cột QUANTITYORDERED:
SELECT 
    QUANTILE(QUANTITYORDERED, 0.25) AS q1,
    QUANTILE(QUANTITYORDERED, 0.75) AS q3
FROM sales_dataset_rfm_prj;
--Tính toán IQR (Q3 - Q1):
SELECT 
    QUANTILE(QUANTITYORDERED, 0.75) - QUANTILE(QUANTITYORDERED, 0.25) AS iqr
FROM sales_dataset_rfm_prj;
--Chọn ngưỡng để xác định outliers, chọn ngưỡng là 1.5*IQR.
--Xóa bản ghi có giá trị nằm ngoài khoảng IQR:
DELETE FROM sales_dataset_rfm_prj
WHERE QUANTITYORDERED < q1 - 1.5*iqr OR QUANTITYORDERED > q3 + 1.5*iqr;
--Hoặc cập nhật giá trị outliers về giá trị giới hạn:
UPDATE sales_dataset_rfm_prj
SET QUANTITYORDERED = q1 - 1.5*iqr
WHERE QUANTITYORDERED < q1 - 1.5*iqr;
UPDATE sales_dataset_rfm_prj
SET QUANTITYORDERED = q3 + 1.5*iqr
WHERE QUANTITYORDERED > q3 + 1.5*iqr;

-- Bước 6: Tạo bảng mới để lưu dữ liệu đã làm sạch
CREATE TABLE SALES_DATASET_RFM_PRJ_CLEAN AS
SELECT *
FROM sales_dataset_rfm_prj;
